### ISSUE TITLE
How to start date Mon - Sun instead of Sunday-Saturday

### ISSUE THREAD

**Issue by syarizat** [Txiaozhe/react-native-lunar-calendar#4]
HI can u help me on this:

I want to start date Monday - Sunday instead of Sunday-Saturday

Thank you very much.

👍

**Comment by Txiaozhe** [comment]
Yes, of cause!
But I have been busy lately, I may not update it in time.
I advice you can try it yourself, if any problem, I will answer!
Thanks！

**Comment by Txiaozhe** [comment]
If you are willing to commit a pr, I am deeply grateful!

**Comment by syarizat** [comment]
Yes i . i just change the part from in getday()
Refer here:
https://www.w3schools.com/jsref/jsref_getday.asp

thank you @Txiaozhe !

**Comment by Txiaozhe** [comment]
Well done! 👍 
Thanks to use!  ：）
